const gallery = [
  {
    id: 1,
    title: "chaton",
    imgpath: "../assets/animal1.jpg",
    description: "chaton mignon",
    likeNumber:0 ,
    category: "animals",
  },
    {
        id: 2,
        title: "sourire",
        imgpath: "../assets/people2.jpg",
        description: "souri a la vie et la vie te sourira",
        likeNumber:0 ,
        category: "people",
    },
    {
        id: 3,
        title: "montagne",
        imgpath: "../assets/nature2.jpg",
        description: "belle montagne",
        likeNumber:0 ,
        category: "nature",
    },
    {
        id: 4,
        title: "un ourse ",
        imgpath: "../assets/animal2.jpg",
        description: "un ourse qui dit salam alikouml",
        likeNumber:0 ,
        category: "animals",
    },
    {
        id: 5,
        title: "pont",
        imgpath: "../assets/architecture4.jpg",
        description: "un pont qui relie deux monde", 
        likeNumber:0 ,
        category: "architecture",
    },
    {
        id: 6,
        title: "Machin Learning",
        imgpath: "../assets/techno2.jpg",
        description: "le futur est la",
        likeNumber:0 ,
        category: "technology",
    },
     {
        id: 7,
        title: "coucher de soleil",
        imgpath: "../assets/nature3.jpg",
        description: "coucher de soleil sur la montagne",
        likeNumber:0 ,
        category: "nature",
     },
    {
        id: 8,
        title: "gratte ciel",
        imgpath: "../assets/architecture2.jpg",
        description: "un gratte ciel a dubai",
        likeNumber:0 ,
        category: "architecture",
     },
     {
        id: 9,
        title: "robot",
        imgpath: "../assets/techno5.jpg",
        description: "robot du futur",
        likeNumber:0 ,
        category: "technology",
     },
     {
        id: 10,
        title: "tigre",
        imgpath: "../assets/animal3.jpg",
        description: "un tigre qui court dans la prairie",
        likeNumber:0 ,
        category: "animals",
     },
     {
        id: 11,
        title: "homme souriant",
        imgpath: "../assets/people3.jpg",
        description: "une femme qui sourit a la vie",
        likeNumber:0 ,
        category: "people",
     },
     // --- Suite de la galerie ---
     {
        id: 12,
        title: "Loup solitaire",
        imgpath: "../assets/animal4.jpg",
        description: "Un loup hurlant à la pleine lune, image puissante.",
        likeNumber:0 ,
        category: "animals",
     },
     {
        id: 13,
        title: "Éléphant d'Afrique",
        imgpath: "../assets/animal5.jpg",
        description: "Un majestueux éléphant marchant au coucher du soleil.",
        likeNumber:0 ,
        category: "animals",
     },
     {
        id: 14,
        title: "Vieille ville",
        imgpath: "../assets/architecture1.jpg",
        description: "Une rue pavée dans une vieille ville européenne.",
        likeNumber:0 ,
        category: "architecture",
     },
     {
        id: 15,
        title: "Pont moderne",
        imgpath: "../assets/architecture3.jpg",
        description: "Structure élégante d'un pont en béton et acier.",
        likeNumber:0 ,
        category: "architecture",
     },
     {
        id: 16,
        title: "Musée d'art",
        imgpath: "../assets/architecture5.jpg",
        description: "Façade d'un musée avec des formes géométriques.",
        likeNumber:0 ,
        category: "architecture",
     },
     {
        id: 17,
        title: "Forêt enchantée",
        imgpath: "../assets/nature1.jpg",
        description: "Chemin à travers une forêt dense et brumeuse.",
        likeNumber:0 ,
        category: "nature",
     },
     {
        id: 18,
        title: "Cascade",
        imgpath: "../assets/nature4.jpg",
        description: "L'eau dévale les rochers avec puissance.",
        likeNumber:0 ,
        category: "nature",
     },
     {
        id: 19,
        title: "Plage tropicale",
        imgpath: "../assets/nature5.jpg",
        description: "Palmiers et sable blanc sous un ciel bleu.",
        likeNumber:0 ,
        category: "nature",
     },
     {
        id: 20,
        title: "Portrait",
        imgpath: "../assets/people1.jpg",
        description: "Un portrait en gros plan avec une expression intense.",
        likeNumber:0 ,
        category: "people",
     },
     {
        id: 21,
        title: "Randonneurs",
        imgpath: "../assets/people4.jpg",
        description: "Des amis admirant le paysage depuis un sommet.",
        likeNumber:0 ,
        category: "people",
     },
     {
        id: 22,
        title: "Étudiant",
        imgpath: "../assets/people5.jpg",
        description: "Un étudiant concentré travaillant sur son ordinateur.",
        likeNumber:0 ,
        category: "people",
     },
     {
        id: 23,
        title: "Code binaire",
        imgpath: "../assets/techno1.jpg",
        description: "Des lignes de code binaire sur un écran noir.",
        likeNumber:0 ,
        category: "technology",
     },
     {
        id: 24,
        title: "Intelligence Artificielle",
        imgpath: "../assets/techno3.jpg",
        description: "Une visualisation abstraite d'un cerveau numérique.",
        likeNumber:0 ,
        category: "technology",
     },
     {
        id: 25,
        title: "Casque VR",
        imgpath: "../assets/techno4.jpg",
        description: "Exploration de la réalité virtuelle et du métavers.",
        likeNumber:0 ,
        category: "technology",
     },
    
];


const category = [
  "nature",
  "architecture",
  "animals",
  "technology",
  "people",

];


export {gallery, category};